# Non-confidential environment specific configurations
development:
  paypal_ipn_postback_uri: "https://www.sandbox.paypal.com/cgi-bin/webscr"

test:
  paypal_ipn_postback_uri: "https://www.sandbox.paypal.com/cgi-bin/webscr"

production:
  paypal_ipn_postback_uri: "https://www.paypal.com/cgi-bin/webscr"

